services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: ./backend
    container_name: pet-app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/getapet
    ports:
      - "3000:3000"
    networks:
      - app_network
  
  front:
    build:
      context: ./frontend 
      dockerfile: Dockerfile  
    container_name: pet-app-front
    ports:
      - "3001:3000"  
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
