services:
  backend:
    build: ./weather-backend
    ports:
      - "5000:5000"
    networks:
      - weather-network

  frontend:
    build: ./weather-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
